development:
  adapter: postgresql
  encoding: utf8
  database: real_tennis_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: real_tennis_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: real_tennis_production
  pool: 5
  username:
  password:
